# Generated by Django 5.0.3 on 2024-03-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=50)),
                ('paquete', models.CharField(choices=[('1', 'paquete A'), ('2', 'paquete B'), ('3', 'paquete C')], max_length=50)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
